### ISSUE TITLE
Crashing Application when Incorrect System Path is Given

### ISSUE THREAD

**Issue by EmilieHK** [EmilieHK/i5-Toolkit-for-Mixed-Reality#7]
When a system path is given in the Virtual Environments inspector, that currently does not exist on the local drive, the error is caught by a timeout. However, the application still crashes afterwards. It would prove helpful to integrate a check whether the path exists, for example using `System.IO.Directory.Exists(myFolderPath)`.

**Comment by JulianStaab** [comment]
This issue was actually caused by a while loop in the EnvironmentsDisplayManager and was fixed by changing it to an if statement.
